server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: aliyara29
    password: Yara2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-must-be-at-least-32-characters-long-for-security}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.aliyara.authservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: app.log