services:

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    profiles: ["default", "all"]
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aliyara29" ]
      interval: 10s
      timeout: 5s
      retries: 5

  supply-db:
    image: postgres:15-alpine
    container_name: supply-db
    profiles: ["default", "all"]
    environment:
      POSTGRES_DB: supply_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - supply-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aliyara29" ]
      interval: 10s
      timeout: 5s
      retries: 5

  production-db:
    image: postgres:15-alpine
    container_name: production-db
    profiles: ["default", "all"]
    environment:
      POSTGRES_DB: production_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - production-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aliyara29"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-db:
    image: postgres:15-alpine
    container_name: customer-db
    profiles: ["default", "all"]
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - customer-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aliyara29"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    profiles: ["default", "all"]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - microservices-network
    depends_on:
      - auth-db
      - supply-db
      - production-db
      - customer-db

  sonar-db:
    image: postgres:15
    container_name: sonar-db
    profiles: ["sonar", "all"]
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    profiles: ["sonar", "all"]
    depends_on:
      - sonar-db
    ports:
      - "9001:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - microservices-network

  jenkins:
    build:
      context: ./jenkins-docker
    container_name: jenkins
    user: root
    profiles: [ "jenkins", "all"]
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    restart: on-failure
    environment:
      JAVA_OPTS: "-Xms1g -Xmx3g"
      DOCKER_HOST: unix:///var/run/docker.sock
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  auth-data:
  supply-data:
  production-data:
  customer-data:
  pgadmin-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar-db-data:
  jenkins_home:
