spring.application.name=supply-service
#spring.datasource.url=jdbc:postgresql://localhost:5432/supplydb
#spring.datasource.username=aliyara29
#spring.datasource.password=Yara2001
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
